checkoutLocation: "gitpodify/workspace-images-dotfiles"
workspaceLocation: "gitpodify"

tasks:
  - name: Workspace Setup
    init: |
      # Well, we have PnP enabled by default and also caches are commited OwO.
      yarn
    before: |
      # Run the setup-dotfiles
      GITPOD_WS_PREBUILD=1 /workspace/gitpodify/workspace-images-dotfiles/docker/base/bin/setup-dotfiles-dir || true
    command:
      ./scripts/ghcr-login.sh || true
  - name: Clone/sync official repo
    command: |
      if [ ! -d "/workspace/gitpodify/gp-workspace-images" ]; then
        git clone https://github.com/gitpod-io/workspace-images "/workspace/gitpodify/gp-workspace-images"
      else
        git -C "/workspace/gitpodify/gp-workspace-images" pull --ff-only
      fi
      exit

vscode:
  extensions:
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - vscode-icons-team.vscode-icons
    - davidanson.vscode-markdownlint
    - timonwong.shellcheck
    - exiasr.hadolint
